name: Publish Plugin

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Print git log
        run: PAGER= git log --oneline --decorate

      - name: Conventional changelog action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-on-empty: "true"
          skip-commit: "true"
          tag-prefix: ''
          output-file: false
          skip-version-file: "true"
          skip-git-pull: "true"
          fallback-version: "0.1.0"

      - name: Fetch new version
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        run: |
          NEW_VERSION=${{ steps.changelog.outputs.version }}
          echo "Creating new version: $NEW_VERSION"
          echo NEW_VERSION=$NEW_VERSION >> $GITHUB_ENV

      - name: Set up JDK 17
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        uses: gradle/actions/setup-gradle@v3

      - name: Build plugin with new version
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        run: ./gradlew clean build -Pversion=${{ steps.changelog.outputs.version }}

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.NEW_VERSION }}
          release_name: ${{ env.NEW_VERSION }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          draft: false
          prerelease: false

      - name: Upload release asset
        id: upload-release-asset
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/libs/curity-plugin-dev-${{ env.NEW_VERSION }}.jar
          asset_name: curity-plugin-dev-${{ env.NEW_VERSION }}.jar
          asset_content_type: application/java-archive

      - name: Publish package
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        run: ./gradlew publish -Pversion=${{ steps.changelog.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}

